# Generated by Django 3.1.3 on 2021-01-17 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='date_pulled')),
                ('symbol', models.CharField(max_length=200, verbose_name='symbol')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('exchange', models.CharField(max_length=200, verbose_name='exchange')),
                ('currency', models.CharField(max_length=200, verbose_name='currency')),
                ('region', models.CharField(max_length=200, verbose_name='region')),
                ('source', models.CharField(max_length=200, verbose_name='source')),
                ('type', models.CharField(max_length=200, verbose_name='type')),
            ],
            options={
                'db_table': 'stock_names',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='date')),
                ('symbol', models.CharField(max_length=10, verbose_name='symbol')),
                ('open', models.FloatField(verbose_name='open')),
                ('high', models.FloatField(verbose_name='high')),
                ('low', models.FloatField(verbose_name='low')),
                ('close', models.FloatField(verbose_name='close')),
                ('volume', models.FloatField(verbose_name='volume')),
                ('source', models.CharField(max_length=200, verbose_name='source')),
                ('stock_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.stockname')),
            ],
            options={
                'db_table': 'historical_stock_data',
            },
        ),
    ]
