# Generated by Django 3.1.3 on 2021-06-07 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='high',
            field=models.FloatField(null=True, verbose_name='high'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='low',
            field=models.FloatField(null=True, verbose_name='low'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='open',
            field=models.FloatField(null=True, verbose_name='open'),
        ),
        migrations.AlterField(
            model_name='stockname',
            name='symbol',
            field=models.CharField(max_length=200, unique=True, verbose_name='symbol'),
        ),
    ]
